In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
! pip install plotly
import plotly.express as px

Collecting plotly
  Downloading plotly-7.1.0-py3-none-any.whl.metadata (8.8 kB)
Requirement already satisfied: narwhals>=1.15.1 in H:\Apps\Python\Python313\Lib\site-packages (from plotly) (2.24.0)
Requirement already satisfied: packaging in H:\Apps\Python\Python313\Lib\site-packages (from plotly) (26.2)
Downloading plotly-7.1.0-py3-none-any.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.7 MB 846.3 kB/s eta 0:00:11
   -- ------------------------------------- 0.5/9.7 MB 846.3 kB/s eta 0:00:11
   --- ------------------------------------ 0.8/9.7 MB 814.8 kB/s eta 0:00:11
   ---- ----------------------------------- 1.0/9.7 MB 864.0 kB/s eta 0:00:11
   ----- ---------------------------------- 1.3/9.7 MB 866.6 kB/s eta 0:00:10
   ----- ---------------------------------- 1.3/9.7 MB 866.6 kB/s eta 0:00:10
   ------ --------------------------------- 1.6/9.7 MB 863.9 kB/s eta 0:00:10
   ------- -------------------------------- 1.8/9.7 MB 863.9 kB/s eta 0:00:10
   ------- -------------------------------- 1.8/9.7 MB 863.9 kB/s eta 0:00:10
   -------- ------------------------------- 2.1/9.7 MB 862.3 kB/s eta 0:00:09
   --------- ------------------------------ 2.4/9.7 MB 862.5 kB/s eta 0:00:09
   ---------- ----------------------------- 2.6/9.7 MB 860.6 kB/s eta 0:00:09
   ---------- ----------------------------- 2.6/9.7 MB 860.6 kB/s eta 0:00:09
   ----------- ---------------------------- 2.9/9.7 MB 861.4 kB/s eta 0:00:08
   ------------ --------------------------- 3.1/9.7 MB 861.4 kB/s eta 0:00:08
   ------------ --------------------------- 3.1/9.7 MB 861.4 kB/s eta 0:00:08
   -------------- ------------------------- 3.4/9.7 MB 859.6 kB/s eta 0:00:08
   --------------- ------------------------ 3.7/9.7 MB 860.2 kB/s eta 0:00:08
   ---------------- ----------------------- 3.9/9.7 MB 860.9 kB/s eta 0:00:07
   ---------------- ----------------------- 3.9/9.7 MB 860.9 kB/s eta 0:00:07
   ----------------- ---------------------- 4.2/9.7 MB 860.9 kB/s eta 0:00:07
   ------------------ --------------------- 4.5/9.7 MB 862.0 kB/s eta 0:00:07
   ------------------ --------------------- 4.5/9.7 MB 862.0 kB/s eta 0:00:07
   ------------------- -------------------- 4.7/9.7 MB 861.8 kB/s eta 0:00:06
   -------------------- ------------------- 5.0/9.7 MB 861.6 kB/s eta 0:00:06
   --------------------- ------------------ 5.2/9.7 MB 860.9 kB/s eta 0:00:06
   --------------------- ------------------ 5.2/9.7 MB 860.9 kB/s eta 0:00:06
   ---------------------- ----------------- 5.5/9.7 MB 861.2 kB/s eta 0:00:05
   ---------------------- ----------------- 5.5/9.7 MB 861.2 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.7 MB 836.2 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.7 MB 836.2 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.7 MB 836.2 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.7 MB 836.2 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.7 MB 836.2 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.7 MB 836.2 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.7 MB 836.2 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.7 MB 836.2 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.7 MB 836.2 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.7 MB 836.2 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.7 MB 836.2 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.7 MB 836.2 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.7 MB 836.2 kB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.7 MB 836.2 kB/s eta 0:00:05
   ------------------------ --------------- 6.0/9.7 MB 604.6 kB/s eta 0:00:07
   ------------------------- -------------- 6.3/9.7 MB 620.2 kB/s eta 0:00:06
   --------------------------- ------------ 6.6/9.7 MB 627.8 kB/s eta 0:00:05
   --------------------------- ------------ 6.6/9.7 MB 627.8 kB/s eta 0:00:05
   ---------------------------- ----------- 6.8/9.7 MB 634.7 kB/s eta 0:00:05
   ----------------------------- ---------- 7.1/9.7 MB 641.0 kB/s eta 0:00:05
   ------------------------------ --------- 7.3/9.7 MB 647.2 kB/s eta 0:00:04
   ------------------------------ --------- 7.3/9.7 MB 647.2 kB/s eta 0:00:04
   ------------------------------- -------- 7.6/9.7 MB 652.9 kB/s eta 0:00:04
   -------------------------------- ------- 7.9/9.7 MB 658.5 kB/s eta 0:00:03
   -------------------------------- ------- 7.9/9.7 MB 658.5 kB/s eta 0:00:03
   --------------------------------- ------ 8.1/9.7 MB 663.2 kB/s eta 0:00:03
   ---------------------------------- ----- 8.4/9.7 MB 668.3 kB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.7 MB 673.1 kB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.7 MB 673.1 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.7 MB 677.4 kB/s eta 0:00:02
   ------------------------------------- -- 9.2/9.7 MB 681.4 kB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.7 MB 681.4 kB/s eta 0:00:01
   -------------------------------------- - 9.4/9.7 MB 685.8 kB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 686.8 kB/s  0:00:13
Installing collected packages: plotly
Successfully installed plotly-7.1.0

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [11]:
comments = pd.read_csv("data/raw/Uscomments.csv", on_bad_lines="skip")

C:\Users\DFIT\AppData\Local\Temp\ipykernel_3832\2142642844.py:1: DtypeWarning: Columns (0: likes, 1: replies) have mixed types. Specify dtype option on import or set low_memory=False.
  comments = pd.read_csv(r"H:\GitHub\youtube-data-analytics\data\raw\Uscomments.csv", on_bad_lines = "skip")

In [12]:
comments

,video_id,comment_text,likes,replies
0,XpVt6Z1Gjjo,Logan Paul it's yo big day ‼️‼️‼️,4,0
1,XpVt6Z1Gjjo,I've been following you from the start of your...,3,0
2,XpVt6Z1Gjjo,Say hi to Kong and maverick for me,3,0
3,XpVt6Z1Gjjo,MY FAN . attendance,3,0
4,XpVt6Z1Gjjo,trending 😉,3,0
...,...,...,...,...
691395,EoejGgUNmVU,Лучшая,1,0
691396,EoejGgUNmVU,qu'est ce que j'aimerais que tu viennes à Roan...,0,0
691397,EoejGgUNmVU,Ven a mexico! 😍 te amo LP,0,0
691398,EoejGgUNmVU,Islığı yeter...,0,0
691399,EoejGgUNmVU,Kocham tą piosenkę😍❤❤❤byłam zakochana po uszy ...,0,0

In [13]:
comments.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
691395     True
691396     True
691397     True
691398    False
691399     True
Length: 691400, dtype: bool

In [17]:
comments[comments.duplicated(keep=False)].sort_values("comment_text")

,video_id,comment_text,likes,replies
577043,xEqCt7GZo7M,,0,0
597655,xEqCt7GZo7M,,0,0
561617,uCVuyIQZ-lA,'Literally' 'like' my bestfriend\nCamila wut?🤔,0,0
581888,uCVuyIQZ-lA,'Literally' 'like' my bestfriend\nCamila wut?🤔,0,0
603266,uCVuyIQZ-lA,'Literally' 'like' my bestfriend\nCamila wut?🤔,0,0
...,...,...,...,...
563768,CX4KuIBmnjI,NaN,0,0
584612,CX4KuIBmnjI,NaN,0,0
605039,CX4KuIBmnjI,NaN,0,0
615625,5qlSfNVp3fU,NaN,0,0
637282,5qlSfNVp3fU,NaN,0,0

In [18]:
comments = comments.drop_duplicates()

In [20]:
comments.isnull().sum()

video_id         0
comment_text    16
likes            0
replies          0
dtype: int64

In [22]:
import warnings
from warnings import filterwarnings
filterwarnings("ignore")

In [21]:
comments.dropna(inplace = True)

In [23]:
comments.isnull().sum()

video_id        0
comment_text    0
likes           0
replies         0
dtype: int64