In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
! pip install plotly
import plotly.express as px

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: plotly in H:\Apps\Python\Python313\Lib\site-packages (7.1.0)
Requirement already satisfied: narwhals>=1.15.1 in H:\Apps\Python\Python313\Lib\site-packages (from plotly) (2.24.0)
Requirement already satisfied: packaging in H:\Apps\Python\Python313\Lib\site-packages (from plotly) (26.2)

In [9]:
comments = pd.read_csv("data/raw/Uscomments.csv", on_bad_lines="skip")

C:\Users\DFIT\AppData\Local\Temp\ipykernel_5080\3282363696.py:1: DtypeWarning: Columns (0: likes, 1: replies) have mixed types. Specify dtype option on import or set low_memory=False.
  comments = pd.read_csv("data/raw/Uscomments.csv", on_bad_lines="skip")

In [10]:
comments

,video_id,comment_text,likes,replies
0,XpVt6Z1Gjjo,Logan Paul it's yo big day ‼️‼️‼️,4,0
1,XpVt6Z1Gjjo,I've been following you from the start of your...,3,0
2,XpVt6Z1Gjjo,Say hi to Kong and maverick for me,3,0
3,XpVt6Z1Gjjo,MY FAN . attendance,3,0
4,XpVt6Z1Gjjo,trending 😉,3,0
...,...,...,...,...
691395,EoejGgUNmVU,Лучшая,1,0
691396,EoejGgUNmVU,qu'est ce que j'aimerais que tu viennes à Roan...,0,0
691397,EoejGgUNmVU,Ven a mexico! 😍 te amo LP,0,0
691398,EoejGgUNmVU,Islığı yeter...,0,0
691399,EoejGgUNmVU,Kocham tą piosenkę😍❤❤❤byłam zakochana po uszy ...,0,0

In [11]:
comments.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
691395     True
691396     True
691397     True
691398    False
691399     True
Length: 691400, dtype: bool

In [12]:
comments[comments.duplicated(keep=False)].sort_values("comment_text")

,video_id,comment_text,likes,replies
577043,xEqCt7GZo7M,,0,0
597655,xEqCt7GZo7M,,0,0
561617,uCVuyIQZ-lA,'Literally' 'like' my bestfriend\nCamila wut?🤔,0,0
581888,uCVuyIQZ-lA,'Literally' 'like' my bestfriend\nCamila wut?🤔,0,0
603266,uCVuyIQZ-lA,'Literally' 'like' my bestfriend\nCamila wut?🤔,0,0
...,...,...,...,...
563768,CX4KuIBmnjI,NaN,0,0
584612,CX4KuIBmnjI,NaN,0,0
605039,CX4KuIBmnjI,NaN,0,0
615625,5qlSfNVp3fU,NaN,0,0
637282,5qlSfNVp3fU,NaN,0,0

In [13]:
comments = comments.drop_duplicates()

In [14]:
comments.isnull().sum()

video_id         0
comment_text    16
likes            0
replies          0
dtype: int64

In [15]:
import warnings
from warnings import filterwarnings
filterwarnings("ignore")

In [16]:
comments.dropna(inplace = True)

In [17]:
comments.isnull().sum()

video_id        0
comment_text    0
likes           0
replies         0
dtype: int64

In [18]:
!pip install nltk
import nltk
nltk.download("vader_lexicon")

Requirement already satisfied: nltk in H:\Apps\Python\Python313\Lib\site-packages (3.10.3)
Requirement already satisfied: defusedxml in H:\Apps\Python\Python313\Lib\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in H:\Apps\Python\Python313\Lib\site-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in H:\Apps\Python\Python313\Lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in H:\Apps\Python\Python313\Lib\site-packages (from nltk) (2026.9.29)
Requirement already satisfied: tqdm in H:\Apps\Python\Python313\Lib\site-packages (from nltk) (4.70.1)
Requirement already satisfied: colorama in H:\Apps\Python\Python313\Lib\site-packages (from tqdm->nltk) (0.4.6)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\DFIT\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [19]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [20]:
sia = SentimentIntensityAnalyzer()

In [22]:
comments["comment_text"]

0                         Logan Paul it's yo big day ‼️‼️‼️
1         I've been following you from the start of your...
2                        Say hi to Kong and maverick for me
3                                       MY FAN . attendance
4                                                trending 😉
                                ...
691359       Lost on you ! 😍\nOH My God I love this song !😭
691366                                        I  LOVE  LP❤️
691392                                *L O S T  O N  Y O U*
691393                                                   <3
691398                                      Islığı yeter...
Name: comment_text, Length: 478691, dtype: str

In [24]:
sia.polarity_scores(" MY FAN . attendance")["compound"]

0.4648

In [25]:
sia.lexicon

{'$:': -1.5,
 '%)': -0.4,
 '%-)': -1.5,
 '&-:': -0.4,
 '&:': -0.7,
 "( '}{' )": 1.6,
 '(%': -0.9,
 "('-:": 2.2,
 "(':": 2.3,
 '((-:': 2.1,
 '(*': 1.1,
 '(-%': -0.7,
 '(-*': 1.3,
 '(-:': 1.6,
 '(-:0': 2.8,
 '(-:<': -0.4,
 '(-:o': 1.5,
 '(-:O': 1.5,
 '(-:{': -0.1,
 '(-:|>*': 1.9,
 '(-;': 1.3,
 '(-;|': 2.1,
 '(8': 2.6,
 '(:': 2.2,
 '(:0': 2.4,
 '(:<': -0.2,
 '(:o': 2.5,
 '(:O': 2.5,
 '(;': 1.1,
 '(;<': 0.3,
 '(=': 2.2,
 '(?:': 2.1,
 '(^:': 1.5,
 '(^;': 1.5,
 '(^;0': 2.0,
 '(^;o': 1.9,
 '(o:': 1.6,
 ")':": -2.0,
 ")-':": -2.1,
 ')-:': -2.1,
 ')-:<': -2.2,
 ')-:{': -2.1,
 '):': -1.8,
 '):<': -1.9,
 '):{': -2.3,
 ');<': -2.6,
 '*)': 0.6,
 '*-)': 0.3,
 '*-:': 2.1,
 '*-;': 2.4,
 '*:': 1.9,
 '*<|:-)': 1.6,
 '*\\0/*': 2.3,
 '*^:': 1.6,
 ',-:': 1.2,
 "---'-;-{@": 2.3,
 '--<--<@': 2.2,
 '.-:': -1.2,
 '..###-:': -1.7,
 '..###:': -1.9,
 '/-:': -1.3,
 '/:': -1.3,
 '/:<': -1.4,
 '/=': -0.9,
 '/^:': -1.0,
 '/o:': -1.4,
 '0-8': 0.1,
 '0-|': -1.2,
 '0:)': 1.9,
 '0:-)': 1.4,
 '0:-3': 1.5,
 '0:03': 1.9,
 '0;^)': 1.6,
 '0_o': -0.3,
 '10q': 2.1,
 '1337': 2.1,
 '143': 3.2,
 '1432': 2.6,
 '14aa41': 2.4,
 '182': -2.9,
 '187': -3.1,
 '2g2b4g': 2.8,
 '2g2bt': -0.1,
 '2qt': 2.1,
 '3:(': -2.2,
 '3:)': 0.5,
 '3:-(': -2.3,
 '3:-)': -1.4,
 '4col': -2.2,
 '4q': -3.1,
 '5fs': 1.5,
 '8)': 1.9,
 '8-d': 1.7,
 '8-o': -0.3,
 '86': -1.6,
 '8d': 2.9,
 ':###..': -2.4,
 ':$': -0.2,
 ':&': -0.6,
 ":'(": -2.2,
 ":')": 2.3,
 ":'-(": -2.4,
 ":'-)": 2.7,
 ':(': -1.9,
 ':)': 2.0,
 ':*': 2.5,
 ':-###..': -2.5,
 ':-&': -0.5,
 ':-(': -1.5,
 ':-)': 1.3,
 ':-))': 2.8,
 ':-*': 1.7,
 ':-,': 1.1,
 ':-.': -0.9,
 ':-/': -1.2,
 ':-<': -1.5,
 ':-d': 2.3,
 ':-D': 2.3,
 ':-o': 0.1,
 ':-p': 1.5,
 ':-[': -1.6,
 ':-\\': -0.9,
 ':-c': -1.3,
 ':-|': -0.7,
 ':-||': -2.5,
 ':-Þ': 0.9,
 ':/': -1.4,
 ':3': 2.3,
 ':<': -2.1,
 ':>': 2.1,
 ':?)': 1.3,
 ':?c': -1.6,
 ':@': -2.5,
 ':d': 2.3,
 ':D': 2.3,
 ':l': -1.7,
 ':o': -0.4,
 ':p': 1.4,
 ':s': -1.2,
 ':[': -2.0,
 ':\\': -1.3,
 ':]': 2.2,
 ':^)': 2.1,
 ':^*': 2.6,
 ':^/': -1.2,
 ':^\\': -1.0,
 ':^|': -1.0,
 ':c': -2.1,
 ':c)': 2.0,
 ':o)': 2.1,
 ':o/': -1.4,
 ':o\\': -1.1,
 ':o|': -0.6,
 ':{': -1.9,
 ':|': -0.4,
 ':}': 2.1,
 ':Þ': 1.1,
 ';)': 0.9,
 ';-)': 1.0,
 ';-*': 2.2,
 ';-]': 0.7,
 ';d': 0.8,
 ';D': 0.8,
 ';]': 0.6,
 ';^)': 1.4,
 '</3': -3.0,
 '<3': 1.9,
 '<:': 2.1,
 '<:-|': -1.4,
 '=)': 2.2,
 '=-3': 2.0,
 '=-d': 2.4,
 '=-D': 2.4,
 '=/': -1.4,
 '=3': 2.1,
 '=d': 2.3,
 '=D': 2.3,
 '=l': -1.2,
 '=\\': -1.2,
 '=]': 1.6,
 '=p': 1.3,
 '=|': -0.8,
 '>-:': -2.0,
 '>.<': -1.3,
 '>:': -2.1,
 '>:(': -2.7,
 '>:)': 0.4,
 '>:-(': -2.7,
 '>:-)': -0.4,
 '>:/': -1.6,
 '>:o': -1.2,
 '>:p': 1.0,
 '>:[': -2.1,
 '>:\\': -1.7,
 '>;(': -2.9,
 '>;)': 0.1,
 '>_>^': 2.1,
 '@:': -2.1,
 '@>-->--': 2.1,
 "@}-;-'---": 2.2,
 'aas': 2.5,
 'aayf': 2.7,
 'afu': -2.9,
 'alol': 2.8,
 'ambw': 2.9,
 'aml': 3.4,
 'atab': -1.9,
 'awol': -1.3,
 'ayc': 0.2,
 'ayor': -1.2,
 'aug-00': 0.3,
 'bfd': -2.7,
 'bfe': -2.6,
 'bff': 2.9,
 'bffn': 1.0,
 'bl': 2.3,
 'bsod': -2.2,
 'btd': -2.1,
 'btdt': -0.1,
 'bz': 0.4,
 'b^d': 2.6,
 'cwot': -2.3,
 "d-':": -2.5,
 'd8': -3.2,
 'd:': 1.2,
 'd:<': -3.2,
 'd;': -2.9,
 'd=': 1.5,
 'doa': -2.3,
 'dx': -3.0,
 'ez': 1.5,
 'fav': 2.0,
 'fcol': -1.8,
 'ff': 1.8,
 'ffs': -2.8,
 'fkm': -2.4,
 'foaf': 1.8,
 'ftw': 2.0,
 'fu': -3.7,
 'fubar': -3.0,
 'fwb': 2.5,
 'fyi': 0.8,
 'fysa': 0.4,
 'g1': 1.4,
 'gg': 1.2,
 'gga': 1.7,
 'gigo': -0.6,
 'gj': 2.0,
 'gl': 1.3,
 'gla': 2.5,
 'gn': 1.2,
 'gr8': 2.7,
 'grrr': -0.4,
 'gt': 1.1,
 'h&k': 2.3,
 'hagd': 2.2,
 'hagn': 2.2,
 'hago': 1.2,
 'hak': 1.9,
 'hand': 2.2,
 'hho1/2k': 1.4,
 'hhoj': 2.0,
 'hhok': 0.9,
 'hugz': 2.0,
 'hi5': 1.9,
 'idk': -0.4,
 'ijs': 0.7,
 'ilu': 3.4,
 'iluaaf': 2.7,
 'ily': 3.4,
 'ily2': 2.6,
 'iou': 0.7,
 'iyq': 2.3,
 'j/j': 2.0,
 'j/k': 1.6,
 'j/p': 1.4,
 'j/t': -0.2,
 'j/w': 1.0,
 'j4f': 1.4,
 'j4g': 1.7,
 'jho': 0.8,
 'jhomf': 1.0,
 'jj': 1.0,
 'jk': 0.9,
 'jp': 0.8,
 'jt': 0.9,
 'jw': 1.6,
 'jealz': -1.2,
 'k4y': 2.3,
 'kfy': 2.3,
 'kia': -3.2,
 'kk': 1.5,
 'kmuf': 2.2,
 'l': 2.0,
 'l&r': 2.2,
 'laoj': 1.3,
 'lmao': 2.9,
 'lmbao': 1.8,
 'lmfao': 2.5,
 'lmso': 2.7,
 'lol': 1.8,
 'lolz': 2.7,
 'lts': 1.6,
 'ly': 2.6,
 'ly4e': 2.7,
 'lya': 3.3,
 'lyb': 3.0,
 'lyl': 3.1,
 'lylab': 2.7,
 'lylas': 2.6,
 'lylb': 1.6,
 'm8': 1.4,
 'mia': -1.2,
 'mml': 2.0,
 'mofo': -2.4,
 'muah': 2.3,
 'mubar': -1.0,
 'musm': 0.9,
 'mwah': 2.5,
 'n1': 1.9,
 'nbd': 1.3,
 'nbif': -0.5,
 'nfc': -2.7,
 'nfw': -2.4,
 'nh': 2.2,
 'nimby': -0.8,
 'nimjd': -0.7,
 'nimq': -0.2,
 'nimy': -1.4,
 'nitl': -1.5,
 'nme': -2.1,
 'noyb': -0.7,
 'np': 1.4,
 'ntmu': 1.4,
 'o-8': -0.5,
 'o-:': -0.3,
 'o-|': -1.1,
 'o.o': -0.8,
 'O.o': -0.6,
 'o.O': -0.6,
 'o:': -0.2,
 'o:)': 1.5,
 'o:-)': 2.0,
 'o:-3': 2.2,
 'o:3': 2.3,
 'o:<': -0.3,
 'o;^)': 1.6,
 'ok': 1.2,
 'o_o': -0.5,
 'O_o': -0.5,
 'o_O': -0.5,
 'pita': -2.4,
 'pls': 0.3,
 'plz': 0.3,
 'pmbi': 0.8,
 'pmfji': 0.3,
 'pmji': 0.7,
 'po': -2.6,
 'ptl': 2.6,
 'pu': -1.1,
 'qq': -2.2,
 'qt': 1.8,
 'r&r': 2.4,
 'rofl': 2.7,
 'roflmao': 2.5,
 'rotfl': 2.6,
 'rotflmao': 2.8,
 'rotflmfao': 2.5,
 'rotflol': 3.0,
 'rotgl': 2.9,
 'rotglmao': 1.8,
 's:': -1.1,
 'sapfu': -1.1,
 'sete': 2.8,
 'sfete': 2.7,
 'sgtm': 2.4,
 'slap': 0.6,
 'slaw': 2.1,
 'smh': -1.3,
 'snafu': -2.5,
 'sob': -1.0,
 'swak': 2.3,
 'tgif': 2.3,
 'thks': 1.4,
 'thx': 1.5,
 'tia': 2.3,
 'tmi': -0.3,
 'tnx': 1.1,
 'true': 1.8,
 'tx': 1.5,
 'txs': 1.1,
 'ty': 1.6,
 'tyvm': 2.5,
 'urw': 1.9,
 'vbg': 2.1,
 'vbs': 3.1,
 'vip': 2.3,
 'vwd': 2.6,
 'vwp': 2.1,
 'wag': -0.2,
 'wd': 2.7,
 'wilco': 0.9,
 'wp': 1.0,
 'wtf': -2.8,
 'wtg': 2.1,
 'wth': -2.4,
 'x-d': 2.6,
 'x-p': 1.7,
 'xd': 2.8,
 'xlnt': 3.0,
 'xoxo': 3.0,
 'xoxozzz': 2.3,
 'xp': 1.6,
 'xqzt': 1.6,
 'xtc': 0.8,
 'yolo': 1.1,
 'yoyo': 0.4,
 'yvw': 1.6,
 'yw': 1.8,
 'ywia': 2.5,
 'zzz': -1.2,
 '[-;': 0.5,
 '[:': 1.3,
 '[;': 1.0,
 '[=': 1.7,
 '\\-:': -1.0,
 '\\:': -1.0,
 '\\:<': -1.7,
 '\\=': -1.1,
 '\\^:': -1.3,
 '\\o/': 2.2,
 '\\o:': -1.2,
 ']-:': -2.1,
 ']:': -1.6,
 ']:<': -2.5,
 '^<_<': 1.4,
 '^urs': -2.8,
 'abandon': -1.9,
 'abandoned': -2.0,
 'abandoner': -1.9,
 'abandoners': -1.9,
 'abandoning': -1.6,
 'abandonment': -2.4,
 'abandonments': -1.7,
 'abandons': -1.3,
 'abducted': -2.3,
 'abduction': -2.8,
 'abductions': -2.0,
 'abhor': -2.0,
 'abhorred': -2.4,
 'abhorrent': -3.1,
 'abhors': -2.9,
 'abilities': 1.0,
 'ability': 1.3,
 'aboard': 0.1,
 'absentee': -1.1,
 'absentees': -0.8,
 'absolve': 1.2,
 'absolved': 1.5,
 'absolves': 1.3,
 'absolving': 1.6,
 'abuse': -3.2,
 'abused': -2.3,
 'abuser': -2.6,
 'abusers': -2.6,
 'abuses': -2.6,
 'abusing': -2.0,
 'abusive': -3.2,
 'abusively': -2.8,
 'abusiveness': -2.5,
 'abusivenesses': -3.0,
 'accept': 1.6,
 'acceptabilities': 1.6,
 'acceptability': 1.1,
 'acceptable': 1.3,
 'acceptableness': 1.3,
 'acceptably': 1.5,
 'acceptance': 2.0,
 'acceptances': 1.7,
 'acceptant': 1.6,
 'acceptation': 1.3,
 'acceptations': 0.9,
 'accepted': 1.1,
 'accepting': 1.6,
 'accepts': 1.3,
 'accident': -2.1,
 'accidental': -0.3,
 'accidentally': -1.4,
 'accidents': -1.3,
 'accomplish': 1.8,
 'accomplished': 1.9,
 'accomplishes': 1.7,
 'accusation': -1.0,
 'accusations': -1.3,
 'accuse': -0.8,
 'accused': -1.2,
 'accuses': -1.4,
 'accusing': -0.7,
 'ache': -1.6,
 'ached': -1.6,
 'aches': -1.0,
 'achievable': 1.3,
 'aching': -2.2,
 'acquit': 0.8,
 'acquits': 0.1,
 'acquitted': 1.0,
 'acquitting': 1.3,
 'acrimonious': -1.7,
 'active': 1.7,
 'actively': 1.3,
 'activeness': 0.6,
 'activenesses': 0.8,
 'actives': 1.1,
 'adequate': 0.9,
 'admirability': 2.4,
 'admirable': 2.6,
 'admirableness': 2.2,
 'admirably': 2.5,
 'admiral': 1.3,
 'admirals': 1.5,
 'admiralties': 1.6,
 'admiralty': 1.2,
 'admiration': 2.5,
 'admirations': 1.6,
 'admire': 2.1,
 'admired': 2.3,
 'admirer': 1.8,
 'admirers': 1.7,
 'admires': 1.5,
 'admiring': 1.6,
 'admiringly': 2.3,
 'admit': 0.8,
 'admits': 1.2,
 'admitted': 0.4,
 'admonished': -1.9,
 'adopt': 0.7,
 'adopts': 0.7,
 'adorability': 2.2,
 'adorable': 2.2,
 'adorableness': 2.5,
 'adorably': 2.1,
 'adoration': 2.9,
 'adorations': 2.2,
 'adore': 2.6,
 'adored': 1.8,
 'adorer': 1.7,
 'adorers': 2.1,
 'adores': 1.6,
 'adoring': 2.6,
 'adoringly': 2.4,
 'adorn': 0.9,
 'adorned': 0.8,
 'adorner': 1.3,
 'adorners': 0.9,
 'adorning': 1.0,
 'adornment': 1.3,
 'adornments': 0.8,
 'adorns': 0.5,
 'advanced': 1.0,
 'advantage': 1.0,
 'advantaged': 1.4,
 'advantageous': 1.5,
 'advantageously': 1.9,
 'advantageousness': 1.6,
 'advantages': 1.5,
 'advantaging': 1.6,
 'adventure': 1.3,
 'adventured': 1.3,
 'adventurer': 1.2,
 'adventurers': 0.9,
 'adventures': 1.4,
 'adventuresome': 1.7,
 'adventuresomeness': 1.3,
 'adventuress': 0.8,
 'adventuresses': 1.4,
 'adventuring': 2.3,
 'adventurism': 1.5,
 'adventurist': 1.4,
 'adventuristic': 1.7,
 'adventurists': 1.2,
 'adventurous': 1.4,
 'adventurously': 1.3,
 'adventurousness': 1.8,
 'adversarial': -1.5,
 'adversaries': -1.0,
 'adversary': -0.8,
 'adversative': -1.2,
 'adversatively': -0.1,
 'adversatives': -1.0,
 'adverse': -1.5,
 'adversely': -0.8,
 'adverseness': -0.6,
 'adversities': -1.5,
 'adversity': -1.8,
 'affected': -0.6,
 'affection': 2.4,
 'affectional': 1.9,
 'affectionally': 1.5,
 'affectionate': 1.9,
 'affectionately': 2.2,
 'affectioned': 1.8,
 'affectionless': -2.0,
 'affections': 1.5,
 'afflicted': -1.5,
 'affronted': 0.2,
 'aggravate': -2.5,
 'aggravated': -1.9,
 'aggravates': -1.9,
 'aggravating': -1.2,
 'aggress': -1.3,
 'aggressed': -1.4,
 'aggresses': -0.5,
 'aggressing': -0.6,
 'aggression': -1.2,
 'aggressions': -1.3,
 'aggressive': -0.6,
 'aggressively': -1.3,
 'aggressiveness': -1.8,
 'aggressivities': -1.4,
 'aggressivity': -0.6,
 'aggressor': -0.8,
 'aggressors': -0.9,
 'aghast': -1.9,
 'agitate': -1.7,
 'agitated': -2.0,
 'agitatedly': -1.6,
 'agitates': -1.4,
 'agitating': -1.8,
 'agitation': -1.0,
 'agitational': -1.2,
 'agitations': -1.3,
 'agitative': -1.3,
 'agitato': -0.1,
 'agitator': -1.4,
 'agitators': -2.1,
 'agog': 1.9,
 'agonise': -2.1,
 'agonised': -2.3,
 'agonises': -2.4,
 'agonising': -1.5,
 'agonize': -2.3,
 'agonized': -2.2,
 'agonizes': -2.3,
 'agonizing': -2.7,
 'agonizingly': -2.3,
 'agony': -1.8,
 'agree': 1.5,
 'agreeability': 1.9,
 'agreeable': 1.8,
 'agreeableness': 1.8,
 'agreeablenesses': 1.3,
 'agreeably': 1.6,
 'agreed': 1.1,
 'agreeing': 1.4,
 'agreement': 2.2,
 'agreements': 1.1,
 'agrees': 0.8,
 'alarm': -1.4,
 'alarmed': -1.4,
 'alarming': -0.5,
 'alarmingly': -2.6,
 'alarmism': -0.3,
 'alarmists': -1.1,
 'alarms': -1.1,
 'alas': -1.1,
 'alert': 1.2,
 'alienation': -1.1,
 'alive': 1.6,
 'allergic': -1.2,
 'allow': 0.9,
 'alone': -1.0,
 'alright': 1.0,
 'amaze': 2.5,
 'amazed': 2.2,
 'amazedly': 2.1,
 'amazement': 2.5,
 'amazements': 2.2,
 'amazes': 2.2,
 'amazing': 2.8,
 'amazon': 0.7,
 'amazonite': 0.2,
 'amazons': -0.1,
 'amazonstone': 1.0,
 'amazonstones': 0.2,
 'ambitious': 2.1,
 'ambivalent': 0.5,
 'amor': 3.0,
 'amoral': -1.6,
 'amoralism': -0.7,
 'amoralisms': -0.7,
 'amoralities': -1.2,
 'amorality': -1.5,
 'amorally': -1.0,
 'amoretti': 0.2,
 'amoretto': 0.6,
 'amorettos': 0.3,
 'amorino': 1.2,
 'amorist': 1.6,
 'amoristic': 1.0,
 'amorists': 0.1,
 'amoroso': 2.3,
 'amorous': 1.8,
 'amorously': 2.3,
 'amorousness': 2.0,
 'amorphous': -0.2,
 'amorphously': 0.1,
 'amorphousness': 0.3,
 'amort': -2.1,
 'amortise': 0.5,
 'amortised': -0.2,
 'amortises': 0.1,
 'amortizable': 0.5,
 'amortization': 0.6,
 'amortizations': 0.2,
 'amortize': -0.1,
 'amortized': 0.8,
 'amortizes': 0.6,
 'amortizing': 0.8,
 'amusable': 0.7,
 'amuse': 1.7,
 'amused': 1.8,
 'amusedly': 2.2,
 'amusement': 1.5,
 'amusements': 1.5,
 'amuser': 1.1,
 'amusers': 1.3,
 'amuses': 1.7,
 'amusia': 0.3,
 'amusias': -0.4,
 'amusing': 1.6,
 'amusingly': 0.8,
 'amusingness': 1.8,
 'amusive': 1.7,
 'anger': -2.7,
 'angered': -2.3,
 'angering': -2.2,
 'angerly': -1.9,
 'angers': -2.3,
 'angrier': -2.3,
 'angriest': -3.1,
 'angrily': -1.8,
 'angriness': -1.7,
 'angry': -2.3,
 'anguish': -2.9,
 'anguished': -1.8,
 'anguishes': -2.1,
 'anguishing': -2.7,
 'animosity': -1.9,
 'annoy': -1.9,
 'annoyance': -1.3,
 'annoyances': -1.8,
 'annoyed': -1.6,
 'annoyer': -2.2,
 'annoyers': -1.5,
 'annoying': -1.7,
 'annoys': -1.8,
 'antagonism': -1.9,
 'antagonisms': -1.2,
 'antagonist': -1.9,
 'antagonistic': -1.7,
 'antagonistically': -2.2,
 'antagonists': -1.7,
 'antagonize': -2.0,
 'antagonized': -1.4,
 'antagonizes': -0.5,
 'antagonizing': -2.7,
 'anti': -1.3,
 'anticipation': 0.4,
 'anxieties': -0.6,
 'anxiety': -0.7,
 'anxious': -1.0,
 'anxiously': -0.9,
 'anxiousness': -1.0,
 'aok': 2.0,
 'apathetic': -1.2,
 'apathetically': -0.4,
 'apathies': -0.6,
 'apathy': -1.2,
 'apeshit': -0.9,
 'apocalyptic': -3.4,
 'apologise': 1.6,
 'apologised': 0.4,
 'apologises': 0.8,
 'apologising': 0.2,
 'apologize': 0.4,
 'apologized': 1.3,
 'apologizes': 1.5,
 'apologizing': -0.3,
 'apology': 0.2,
 'appall': -2.4,
 'appalled': -2.0,
 'appalling': -1.5,
 'appallingly': -2.0,
 'appalls': -1.9,
 'appease': 1.1,
 'appeased': 0.9,
 'appeases': 0.9,
 'appeasing': 1.0,
 'applaud': 2.0,
 'applauded': 1.5,
 'applauding': 2.1,
 'applauds': 1.4,
 'applause': 1.8,
 'appreciate': 1.7,
 'appreciated': 2.3,
 'appreciates': 2.3,
 'appreciating': 1.9,
 'appreciation': 2.3,
 'appreciations': 1.7,
 'appreciative': 2.6,
 'appreciatively': 1.8,
 'appreciativeness': 1.6,
 'appreciator': 2.6,
 'appreciators': 1.5,
 'appreciatory': 1.7,
 'apprehensible': 1.1,
 'apprehensibly': -0.2,
 'apprehension': -2.1,
 'apprehensions': -0.9,
 'apprehensively': -0.3,
 'apprehensiveness': -0.7,
 'approval': 2.1,
 'approved': 1.8,
 'approves': 1.7,
 'ardent': 2.1,
 'arguable': -1.0,
 'arguably': -1.0,
 'argue': -1.4,
 'argued': -1.5,
 'arguer': -1.6,
 'arguers': -1.4,
 'argues': -1.6,
 'arguing': -2.0,
 'argument': -1.5,
 'argumentative': -1.5,
 'argumentatively': -1.8,
 'argumentive': -1.5,
 'arguments': -1.7,
 'arrest': -1.4,
 'arrested': -2.1,
 'arrests': -1.9,
 'arrogance': -2.4,
 'arrogances': -1.9,
 'arrogant': -2.2,
 'arrogantly': -1.8,
 'ashamed': -2.1,
 'ashamedly': -1.7,
 'ass': -2.5,
 'assassination': -2.9,
 'assassinations': -2.7,
 'assault': -2.8,
 'assaulted': -2.4,
 'assaulting': -2.3,
 'assaultive': -2.8,
 'assaults': -2.5,
 'asset': 1.5,
 'assets': 0.7,
 'assfucking': -2.5,
 'assholes': -2.8,
 'assurance': 1.4,
 'assurances': 1.4,
 'assure': 1.4,
 'assured': 1.5,
 'assuredly': 1.6,
 'assuredness': 1.4,
 'assurer': 0.9,
 'assurers': 1.1,
 'assures': 1.3,
 'assurgent': 1.3,
 'assuring': 1.6,
 'assuror': 0.5,
 'assurors': 0.7,
 'astonished': 1.6,
 'astound': 1.7,
 'astounded': 1.8,
 'astounding': 1.8,
 'astoundingly': 2.1,
 'astounds': 2.1,
 'attachment': 1.2,
 'attachments': 1.1,
 'attack': -2.1,
 'attacked': -2.0,
 'attacker': -2.7,
 'attackers': -2.7,
 'attacking': -2.0,
 'attacks': -1.9,
 'attract': 1.5,
 'attractancy': 0.9,
 'attractant': 1.3,
 'attractants': 1.4,
 'attracted': 1.8,
 'attracting': 2.1,
 'attraction': 2.0,
 'attractions': 1.8,
 'attractive': 1.9,
 'attractively': 2.2,
 'attractiveness': 1.8,
 'attractivenesses': 2.1,
 'attractor': 1.2,
 'attractors': 1.2,
 'attracts': 1.7,
 'audacious': 0.9,
 'authority': 0.3,
 'aversion': -1.9,
 'aversions': -1.1,
 'aversive': -1.6,
 'aversively': -0.8,
 'avert': -0.7,
 'averted': -0.3,
 'averts': -0.4,
 'avid': 1.2,
 'avoid': -1.2,
 'avoidance': -1.7,
 'avoidances': -1.1,
 'avoided': -1.4,
 'avoider': -1.8,
 'avoiders': -1.4,
 'avoiding': -1.4,
 'avoids': -0.7,
 'await': 0.4,
 'awaited': -0.1,
 'awaits': 0.3,
 'award': 2.5,
 'awardable': 2.4,
 'awarded': 1.7,
 'awardee': 1.8,
 'awardees': 1.2,
 'awarder': 0.9,
 'awarders': 1.3,
 'awarding': 1.9,
 'awards': 2.0,
 'awesome': 3.1,
 'awful': -2.0,
 'awkward': -0.6,
 'awkwardly': -1.3,
 'awkwardness': -0.7,
 'axe': -0.4,
 'axed': -1.3,
 'backed': 0.1,
 'backing': 0.1,
 'backs': -0.2,
 'bad': -2.5,
 'badass': -0.6,
 'badly': -2.1,
 'bailout': -0.4,
 'bamboozle': -1.5,
 'bamboozled': -1.5,
 'bamboozles': -1.5,
 'ban': -2.6,
 'banish': -1.9,
 'bankrupt': -2.6,
 'bankster': -2.1,
 'banned': -2.0,
 'bargain': 0.8,
 'barrier': -0.5,
 'bashful': -0.1,
 'bashfully': 0.2,
 'bashfulness': -0.8,
 'bastard': -2.5,
 'bastardies': -1.8,
 'bastardise': -2.1,
 'bastardised': -2.3,
 'bastardises': -2.3,
 'bastardising': -2.6,
 'bastardization': -2.4,
 'bastardizations': -2.1,
 'bastardize': -2.4,
 'bastardized': -2.0,
 'bastardizes': -1.8,
 'bastardizing': -2.3,
 'bastardly': -2.7,
 'bastards': -3.0,
 'bastardy': -2.7,
 'battle': -1.6,
 'battled': -1.2,
 'battlefield': -1.6,
 'battlefields': -0.9,
 'battlefront': -1.2,
 'battlefronts': -0.8,
 'battleground': -1.7,
 'battlegrounds': -0.6,
 'battlement': -0.4,
 'battlements': -0.4,
 'battler': -0.8,
 'battlers': -0.2,
 'battles': -1.6,
 'battleship': -0.1,
 'battleships': -0.5,
 'battlewagon': -0.3,
 'battlewagons': -0.5,
 'battling': -1.1,
 'beaten': -1.8,
 'beatific': 1.8,
 'beating': -2.0,
 'beaut': 1.6,
 'beauteous': 2.5,
 'beauteously': 2.6,
 'beauteousness': 2.7,
 'beautician': 1.2,
 'beauticians': 0.4,
 ...}

In [28]:
def analyze_comment_sentiment(comment):
    compound = sia.polarity_scores(comment)["compound"]

    if compound > 0.05:
        label = "Positive 😊"
        insight = "the comment expresses positive emotion or approval"

    elif compound < -0.05:
        label = "Negative 😡"
        insight = "the comment shows dis-satisfaction or negative emotion"

    else:
        label = "Neutral 😐"
        insight = "The comment is informational or emotionally neutral"

    return {
        "label": label,
        "score": compound,
        "insight": insight,
    }

In [29]:
analyze_comment_sentiment(" MY FAN . attendance")

{'label': 'Positive 😊',
 'socre': 0.4648,
 'insight': 'the comment expresses positive emotion or approval'}